# Generated by Django 3.0.1 on 2019-12-25 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from_website', models.TextField()),
                ('property_name', models.TextField()),
                ('address', models.TextField()),
                ('price', models.FloatField()),
                ('including_utilies', models.BooleanField()),
                ('area', models.FloatField()),
                ('number_of_bedrooms', models.IntegerField()),
                ('state_of_furnishing', models.TextField()),
                ('available_from', models.TextField()),
                ('offered_since', models.TextField()),
                ('energy_label', models.TextField()),
                ('description_from_tenant', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Home')),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('distance_item_name', models.TextField()),
                ('distance_in_meters', models.FloatField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.Home')),
            ],
        ),
    ]
