# Generated by Django 3.0.1 on 2019-12-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='property_source_url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='home',
            name='property_website_source',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='home',
            name='tenant_contact_information',
            field=models.TextField(default=''),
        ),
    ]
