# Generated by Django 3.0.1 on 2019-12-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0002_auto_20191225_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='region',
            field=models.TextField(default=''),
        ),
    ]
