# Generated by Django 3.0.1 on 2019-12-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0003_home_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='address',
        ),
        migrations.AddField(
            model_name='home',
            name='street',
            field=models.TextField(default=''),
        ),
    ]
