# Generated by Django 3.0.1 on 2019-12-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0004_auto_20191225_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='postcode',
            field=models.TextField(default=''),
        ),
    ]
