# Generated by Django 3.0.1 on 2019-12-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0005_home_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='energy_label',
            field=models.TextField(null=True),
        ),
    ]
