# Generated by Django 3.0.1 on 2020-01-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0006_auto_20191225_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='city',
            field=models.TextField(default=''),
        ),
    ]
