# Generated by Django 3.0.1 on 2020-01-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0008_auto_20200101_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='type_of_property',
            field=models.TextField(default=''),
        ),
    ]
